<?php 

if (isset($_POST["Mensaje"])) { //CON ISSET VALIDO QUE LA VARIABLE NO ESTÉ VACÍA.
	if (strlen($_POST["Mensaje"]) > 5) {
		include "MayorA5.html"; // AL HACER EL INCLUDE VA A ESE ARCHIVO Y EJECUTA LO ALLÍ DECLARADO
	}
	else{
		include "MenorA5.html";	// AL HACER EL INCLUDE VA A ESE ARCHIVO Y EJECUTA LO ALLÍ DECLARADO
	}
	//echo $_POST ["Mensaje"];
}

echo "<br><br><br>Muestro var_dump para validar los datos:<br>";
var_dump($_REQUEST);
var_dump($_POST["Mensaje"]);

//EL INCLUDE VA A BUSCAR LA PÁGINA CORRESPONDIENTE SEGÚN LAS VALIDACIONES NECESARIAS Y "TRAE" LOS CÓDIGOS DE HTML EJECUTÁNDOLOS DEBAJO DEL INCLUDE.

//SI QUIERO UTILIZAR LAS VARIABLES EN LOS ARCHIVOS INCLUIDOS ESTOS DEBERÍAN SER PHP.

 ?>